spring:
#profiles:
#  active: production
 application:
  name: ms-tag
 datasource:
  url: jdbc:${DB_VENDOR}://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
   hibernate:
    ddl-auto: update
      # create-drop: crea tabelle all'avvio dell'applicazione e le distugge quando la stoppo
      # validated: confronta le entità del progetto con le tabelle del db: se ci sono anomalie, solleva eccezione
    # none: da usare in ambiente di produzione: non viene riportata alcuna modifica al db
    # update: aggiorna il db con le tabelle/colonne nuove; non elimina colonne che non hanno più corrispondenza con l'entità
   properties:
    dialect: org.hibernate.dialect.MySQLDialect
    hibernate:
     format_sql: true
   show-sql: true
   open-in-view: false
   defer-datasource-initialization: true

  # all'avvio dell'applicazione viene eseguito data.sql presente in resource
  sql.init.mode: never

server:
 port: 8081
 servlet:
  context-path: /ms-tag
 compression:
  enabled: true
  mime-types: application/json,text/plain
  min-response-size: 2048

eureka:
 instance:
  hostname: localhost
  prefer-ip-address: true
 client:
  registerWithEureka: true
  serviceUrl:
   default-zone: http://${eureka.instance.hostname}:8761/eureka/


logging:
 level:
  org.springframework: debug
  it.cgmconsulting.tag: debug