spring:
  application:
    name: ms-auth
  datasource:
    url: jdbc:${DB_VENDOR}://${DB_HOSTNAME}:${DB_PORT}/${DB_NAME}?ssl-mode=REQUIRED
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    hibernate:
      ddl-auto: update
        # create-drop: crea tabelle all'avvio dell'applicazione e le distugge quando la stoppo
        # validated: confronta le entità del progetto con le tabelle del db: se ci sono anomalie, solleva eccezione
      # none: da usare in ambiente di produzione: non viene riportata alcuna modifica al db
      # update: aggiorna il db con le tabelle/colonne nuove; non elimina colonne che non hanno più corrispondenza con l'entità
    properties:
      dialect: org.hibernate.dialect.MySQLDialect
      hibernate:
        format_sql: true
    show-sql: true
    open-in-view: false
    defer-datasource-initialization: true

  # all'avvio dell'applicazione viene eseguito data.sql presente in resource
  sql.init.mode: never

server:
  port: 0
  servlet:
    context-path: /ms-auth
  compression:
    enabled: true
    min-response-size: 2048
    mime-types: text/plain,application/json


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 61
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/

logging:
  level:
    org.springframework: info
    it.cgmconsulting.auth: info
    org.hibernate.orm.jdbc.bind: trace

management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: "*"
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  # ZIPKIN
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 0.95

info:
  app:
    # valori recuperati dal pom.xml
    name: "@project.name@"
    description: "@project.description@"
    version: "@project.version@"

# CUSTOM PROPERTIES
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}
      # 4 ORE in millisecondi
      expiration: 14400000
    internalToken: a95dbd9829fd3690e7bba2eed667c3d112e23ccf8967782662a9c92cacbdd329

# CONFIGURAZIONE CIRCUIT BREAKER
resilience4j.circuitbreaker:
  instances:
    a-tempo: #nomi arbitrari per le istanze dei controlli
      registerHealthIndicator: true
      # Apertura del circuito se la request impiega più tempo di quanto stimato
      sliding-window-type: TIME_BASED
      # Numero di tentativi di request
      sliding-window-size: 1
      # Soglia - in percentuale - di fallimenti (se al 100%, basta che la chiamata al microservizio fallisca una volta sola)
      slow-call-rate-threshold: 100
      # Un'interazione è considerata lenta se impiega più di n secondi a rispondere
      slow-call-duration-threshold: 2s
      # Tempo per passare dallo stato di OPEN a HALF_OPEN
      wait-duration-in-open-state: 60s
      minimum-number-of-calls: 1
      # Numero massimo di request permesse in stato HALF_OPEN
      permitted-number-of-calls-in-half-open-state: 1
      automatic-transition-from-open-to-half-open-enabled: true
    a-tentativi: #nome seconda istanza arbitrario
      register-health-indicator: true
      # Apertura del circuito se la request fallisce n volte
      sliding-window-type: COUNT_BASED
      # Numero di tentativi di request
      sliding-window-size: 1
      # Soglia - in percentuale - di fallimenti (se al 100%, basta che la chiamata al microservizio fallisca una volta sola)
      failure-rate-threshold: 100
      wait-duration-in-open-state: 60s
      permitted-number-of-calls-in-half-open-state: 1
      automatic-transition-from-open-to-half-open-enabled: true