eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 61
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/
management:
  endpoint:
    health:
      show-details: always
  endpoints:
    web:
      exposure:
        include: health,info,tracing
  info:
    java:
      enabled: true
    os:
      enabled: true
    env:
      enabled: true
  # ZIPKIN
  zipkin:
    tracing:
      endpoint: http://localhost:9411/api/v2/spans
  tracing:
    enabled: true
    sampling:
      probability: 0.1


logging:
  level:
    org.springframework: info
    it.cgmconsulting.gateway: info

server:
  port: 9090

spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-tag
            # lb = load balancer
            uri: lb://ms-tag
            predicates:
              - Path=/ms-tag/**
          - id: ms-auth
            uri: lb://ms-auth
            predicates:
              - Path=/ms-auth/**

# CUSTOM PROPERTIES
application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY}

