spring:
  application:
    name: ms-gateway
  cloud:
    gateway:
      mvc:
        routes:
          - id: ms-tag
            uri: lb://ms-tag
            predicates:
              - Path=/ms-tag/**
          - id: ms-auth
            uri: lb://ms-auth
            predicates:
              - Path=/ms-auth/**


server:
  port: 9090


eureka:
  instance:
    hostname: localhost
    prefer-ip-address: true
    lease-renewal-interval-in-seconds: 30
    lease-expiration-duration-in-seconds: 61
  client:
    register-with-eureka: true
    service-url:
      default-zone: http://${eureka.instance.hostname}:8761/eureka/

logging:
  level:
    org.springframework: info
    it.cgmconsulting.gateway: info